import {test}from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{PGlite}from'@electric-sql/pglite';
import{demoSeed,POOL_ONE,POOL_TWO}from'../lib/seed';import{quoteSlot}from'../lib/pricing';
const ADMIN='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',BUYER='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',OTHER='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
async function database(combined=false){const db=new PGlite();try{await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);create function auth.uid()returns uuid language sql stable as 'select null::uuid';create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid,bucket_id text);alter table storage.objects enable row level security;`);if(combined){await db.exec(readFileSync('supabase/install/PLYDECK_NEW_PROJECT_SETUP.sql','utf8'));}else{for(const file of ['001_plydeck.sql','002_replacement_slots.sql','003_whatsapp_notifications.sql','004_whatsapp_delivery_fixes.sql'])await db.exec(readFileSync(`supabase/migrations/${file}`,'utf8'));await db.exec(readFileSync('supabase/seed.sql','utf8'));}await db.query('insert into auth.users values($1),($2),($3)',[ADMIN,BUYER,OTHER]);await db.query('insert into admins(user_id)values($1)',[ADMIN]);for(const id of [BUYER,OTHER])await db.query(`insert into profiles(id,business_name,contact_name,phone,gstin,address,city,state,pincode,whatsapp_opt_in)values($1,'Demo business','Buyer','9876543210','29ABCDE1234F1Z5','Demo address 123','Bengaluru','Karnataka','560001',true)`,[id]);await db.exec(`update pools set status='live'`);return db;}catch(e){await db.close();throw e;}}
async function reserve(db:PGlite,poolId:string,slots:number[],qty=80,user=BUYER){const{rows}=await db.query<any>('select * from pools where id=$1',[poolId]);const p=rows[0],q=quoteSlot(p,qty,slots.length);const result=await db.query<any>('select reserve_slots($1,$2,$3,$4,$5,$6)as result',[user,poolId,slots,qty,JSON.stringify(q),p.updated_at]);return result.rows[0].result;}
let paymentCounter=0;
async function pay(db:PGlite,order:any,stage:string){const{rows}=await db.query<any>('select prepare_payment($1,$2,$3)as result',[order.id,order.user_id,stage]);const a=rows[0].result,remote=`order_${++paymentCounter}`,payment=`pay_${paymentCounter}`;await db.query('update payment_attempts set razorpay_order_id=$1 where id=$2',[remote,a.id]);const result=await db.query<any>('select apply_payment($1,$2,$3,$4)as result',[remote,payment,a.amount,'INR']);return{...result.rows[0].result,remote,payment,amount:a.amount};}
test('database: slot exclusivity, immutable quote, payment idempotency and full refund on cancellation',async()=>{const db=await database();try{const o=await reserve(db,POOL_ONE,[1]);await assert.rejects(()=>reserve(db,POOL_ONE,[1],80,OTHER),/reserved/);await assert.rejects(()=>db.query('select prepare_payment($1,$2,$3)',[o.id,BUYER,'dispatch']),/QC/);const p=await pay(db,o,'booking');assert.equal(p.verified,true);const duplicate=await db.query<any>('select apply_payment($1,$2,$3,$4)as result',[p.remote,p.payment,p.amount,'INR']);assert.equal(duplicate.rows[0].result.duplicate,true);const total=await db.query<any>('select paid_amount from orders where id=$1',[o.id]);assert.equal(Number(total.rows[0].paid_amount),o.quote.stages.booking);const pool=demoSeed().pools[0];await assert.rejects(()=>db.query('select save_pool($1,$2)',[ADMIN,JSON.stringify(pool)]),/locked/);await db.query('select cancel_order($1,$2)',[BUYER,o.id]);const r=await db.query<any>('select * from refunds where order_id=$1',[o.id]);assert.equal(Number(r.rows[0].amount),o.quote.stages.booking);await assert.rejects(()=>db.query('select prepare_refund($1,$2,$3,$4)',[r.rows[0].id,ADMIN,1,'Wrong deduction']),/full refund/);await reserve(db,POOL_ONE,[1],80,OTHER);}finally{await db.close();}});
test('database: shared tonnage blocks the ninth all-primary slot and expired payment is refunded',async()=>{const db=await database();try{await reserve(db,POOL_ONE,[1,2,3,4,5],100);await reserve(db,POOL_TWO,[1,2,3],100);await assert.rejects(()=>reserve(db,POOL_TWO,[4],100),/payload/);const o=await reserve(db,POOL_TWO,[4],60);const a=await db.query<any>('select prepare_payment($1,$2,$3)as result',[o.id,BUYER,'booking']);await db.query("update payment_attempts set razorpay_order_id='order_late'where id=$1",[a.rows[0].result.id]);await db.query("update orders set expires_at=now()-interval '1 minute'where id=$1",[o.id]);await db.exec('select expire_holds()');await reserve(db,POOL_TWO,[4],60,OTHER);const r=await db.query<any>("select apply_payment('order_late','pay_late',$1,'INR')as result",[o.quote.stages.booking]);assert.equal(r.rows[0].result.verified,false);assert.equal(r.rows[0].result.refund_pending,true);}finally{await db.close();}});
test('database: server-only RPC permissions, admin protection, QC and 100% dispatch gate',async()=>{const db=await database();try{const grants=await db.query<any>("select has_function_privilege('authenticated','reserve_slots(uuid,uuid,integer[],integer,jsonb,timestamptz)','EXECUTE')as allowed");assert.equal(grants.rows[0].allowed,false);await assert.rejects(()=>db.query('select transition_pool($1,$2,$3,$4)',[BUYER,POOL_ONE,'cancel','No authority']),/Administrator/);const o=await reserve(db,POOL_ONE,[1,2,3,4,5]);await pay(db,o,'booking');await db.query('select transition_pool($1,$2,$3,$4)',[ADMIN,POOL_ONE,'request_confirmation','']);await assert.rejects(()=>db.query('select transition_pool($1,$2,$3,$4)',[ADMIN,POOL_ONE,'confirm','']),/50%/);await pay(db,o,'confirmation');await db.query('select transition_pool($1,$2,$3,$4)',[ADMIN,POOL_ONE,'confirm','']);await assert.rejects(()=>db.query('select prepare_payment($1,$2,$3)',[o.id,BUYER,'dispatch']),/QC/);await db.query('select transition_pool($1,$2,$3,$4)',[ADMIN,POOL_ONE,'qc','Batch checked, sheet count and dimensions accepted.']);await assert.rejects(()=>db.query('select transition_pool($1,$2,$3,$4)',[ADMIN,POOL_ONE,'dispatch','']),/full payments/);await pay(db,o,'dispatch');await db.query('select transition_pool($1,$2,$3,$4)',[ADMIN,POOL_ONE,'dispatch','']);const result=await db.query<any>('select status from orders where id=$1',[o.id]);assert.equal(result.rows[0].status,'dispatched');}finally{await db.close();}});
test('database: post-QC default has notice period, FIFO offer, fixed mix and replacement payment stages',async()=>{const db=await database();try{const o=await reserve(db,POOL_ONE,[1,2,3,4,5],70);await pay(db,o,'booking');await db.query('select transition_pool($1,$2,$3,$4)',[ADMIN,POOL_ONE,'request_confirmation','']);await pay(db,o,'confirmation');await db.query('select transition_pool($1,$2,$3,$4)',[ADMIN,POOL_ONE,'confirm','']);await db.query('select transition_pool($1,$2,$3,$4)',[ADMIN,POOL_ONE,'qc','Batch inspected and accepted with 70:30 mix per slot.']);await db.exec("update pools set payment_due_at=now()-interval '1 hour'where code='BLR-OEM-001'");await assert.rejects(()=>db.query('select default_order($1,$2,$3,$4)',[ADMIN,o.id,'default','Commitment review required.']),/cure period/);await db.query('select default_order($1,$2,$3,$4)',[ADMIN,o.id,'default_notice','Written notice reference 001 delivered.']);await db.query("update orders set default_notice_at=now()-interval '49 hours'where id=$1",[o.id]);await db.query('select default_order($1,$2,$3,$4)',[ADMIN,o.id,'default','Review costs and resale recovery.']);await db.query('select join_waitlist($1,$2)',[OTHER,POOL_ONE]);await db.query('select offer_next($1,$2)',[ADMIN,POOL_ONE]);await assert.rejects(()=>reserve(db,POOL_ONE,[1],80,OTHER),/original QC/);const replacement=await reserve(db,POOL_ONE,[1],70,OTHER);assert.equal(replacement.replacement,true);await pay(db,replacement,'booking');await pay(db,replacement,'confirmation');await pay(db,replacement,'dispatch');}finally{await db.close();}});
test('database: refund tasks retry without duplication and reviewed cancellation releases stock',async()=>{const db=await database();try{const o=await reserve(db,POOL_ONE,[1,2,3,4,5]);await pay(db,o,'booking');await db.query('select transition_pool($1,$2,$3,$4)',[ADMIN,POOL_ONE,'request_confirmation','']);await pay(db,o,'confirmation');await db.query('select transition_pool($1,$2,$3,$4)',[ADMIN,POOL_ONE,'confirm','']);await db.query('select cancel_order($1,$2)',[BUYER,o.id]);const{rows:r}=await db.query<any>('select * from refunds where order_id=$1',[o.id]);const args=[r[0].id,ADMIN,o.quote.stages.booking,'Refund booking amount; reviewed supplier commitments and recovery.'];const first=await db.query<any>('select prepare_refund($1,$2,$3,$4)as result',args);const second=await db.query<any>('select prepare_refund($1,$2,$3,$4)as result',args);assert.equal(first.rows[0].result[0].id,second.rows[0].result[0].id);const allocated=await db.query<any>('select count(*)as n from slot_allocations where order_id=$1',[o.id]);assert.equal(Number(allocated.rows[0].n),0);const vacated=await db.query<any>('select count(*)as n from vacated_slots where source_order=$1',[o.id]);assert.equal(Number(vacated.rows[0].n),5);}finally{await db.close();}});

test('database: opted-in payment events enter WhatsApp outbox and can be claimed once',async()=>{const db=await database();try{const o=await reserve(db,POOL_ONE,[1]);await pay(db,o,'booking');const rows=await db.query<any>('select purpose,status,recipient_phone from whatsapp_messages where order_id=$1',[o.id]);assert.equal(rows.rows.length,1);assert.equal(rows.rows[0].purpose,'booking_received');assert.equal(rows.rows[0].status,'queued');assert.equal(rows.rows[0].recipient_phone,'919876543210');const claimed=await db.query<any>('select * from claim_whatsapp_messages(10)');assert.equal(claimed.rows.length,1);assert.equal(claimed.rows[0].status,'sending');const second=await db.query<any>('select * from claim_whatsapp_messages(10)');assert.equal(second.rows.length,0);}finally{await db.close();}});

test('WhatsApp: QC asks for the outstanding 50%, uses IST, and paid reminders are skipped',async()=>{const db=await database();try{
 const o=await reserve(db,POOL_ONE,[1,2,3,4,5]);await pay(db,o,'booking');
 await db.query('select transition_pool($1,$2,$3,$4)',[ADMIN,POOL_ONE,'request_confirmation','']);
 await pay(db,o,'confirmation');await db.query('select transition_pool($1,$2,$3,$4)',[ADMIN,POOL_ONE,'confirm','']);
 await db.query('select transition_pool($1,$2,$3,$4)',[ADMIN,POOL_ONE,'qc','Batch checked and accepted against the specification.']);
 const q=await db.query<any>("select * from whatsapp_messages where purpose='qc_due'");
 assert.equal(Number(q.rows[0].variables.amount),o.quote.stages.dispatch/100);assert.match(q.rows[0].variables.due_at,/ IST$/);
 await pay(db,o,'dispatch');await db.query('select * from claim_whatsapp_messages(20)');
 const statuses=await db.query<any>("select status from whatsapp_messages where purpose in('confirmation_due','qc_due')");assert.ok(statuses.rows.every(r=>r.status==='skipped'));
}finally{await db.close();}});

test('WhatsApp: no consent means no event; withdrawn consent prevents sending an existing event',async()=>{const db=await database();try{
 await db.query('update profiles set whatsapp_opt_in=false where id=$1',[BUYER]);const o=await reserve(db,POOL_ONE,[1]);await pay(db,o,'booking');
 assert.equal((await db.query<any>('select * from whatsapp_messages')).rows.length,0);
 const second=await reserve(db,POOL_ONE,[2],80,OTHER);await pay(db,second,'booking');
 await db.query('update profiles set whatsapp_opt_in=false where id=$1',[OTHER]);assert.equal((await db.query<any>('select * from claim_whatsapp_messages(10)')).rows.length,0);
 assert.equal((await db.query<any>('select status from whatsapp_messages')).rows[0].status,'skipped');
}finally{await db.close();}});

test('WhatsApp: refund stages have separate event keys and retries cannot create another copy',async()=>{const db=await database();try{
 const o=await reserve(db,POOL_ONE,[1]);await pay(db,o,'booking');await db.query('select cancel_order($1,$2)',[BUYER,o.id]);
 const refund=(await db.query<any>('select * from refunds where order_id=$1',[o.id])).rows[0];
 await db.query('select prepare_refund($1,$2,$3,$4)',[refund.id,ADMIN,o.quote.stages.booking,'Full refund approved.']);
 await db.query("update refunds set status='refunded' where id=$1",[refund.id]);
 assert.equal((await db.query<any>("select * from whatsapp_messages where purpose like 'refund_update:%'")).rows.length,2);
 const msg=(await db.query<any>("select * from whatsapp_messages where purpose='booking_received'")).rows[0];
 await db.query("update whatsapp_messages set status='failed' where id=$1",[msg.id]);
 await db.query('select queue_whatsapp_event($1,$2,$3,$4,$5,$6)',[msg.order_id,msg.pool_id,msg.user_id,msg.purpose,msg.template_name,JSON.stringify(msg.variables)]);
 assert.equal((await db.query<any>("select * from whatsapp_messages where purpose='booking_received'")).rows.length,1);
}finally{await db.close();}});

test('WhatsApp: webhook replay is atomic, statuses cannot regress after read, and STOP revokes consent',async()=>{const db=await database();try{
 const o=await reserve(db,POOL_ONE,[1]);await pay(db,o,'booking');const m=(await db.query<any>('select * from whatsapp_messages')).rows[0];
 const payload=(status:string)=>({entry:[{changes:[{value:{statuses:[{id:'wamid_test',biz_opaque_callback_data:m.id,status,timestamp:'1789000000'}]}}]}]});
 const call=async(hash:string,event:any)=>db.query<any>('select apply_whatsapp_webhook($1,$2) as result',[hash,JSON.stringify(event)]);
 await call('read_1',payload('read'));await call('late_sent',payload('sent'));await call('late_failed',payload('failed'));
 assert.equal((await db.query<any>('select status from whatsapp_messages where id=$1',[m.id])).rows[0].status,'read');
 assert.equal((await call('read_1',payload('read'))).rows[0].result.duplicate,true);
 await assert.rejects(()=>call('broken',{entry:{invalid:true}}));assert.equal((await db.query<any>("select * from whatsapp_webhook_events where event_hash='broken'")).rows.length,0);
 await call('stop',{entry:[{changes:[{value:{messages:[{id:'inbound_stop',from:'919876543210',type:'text',text:{body:'STOP'}}]}}]}]});
 assert.ok((await db.query<any>('select whatsapp_opt_in from profiles')).rows.every(r=>r.whatsapp_opt_in===false));
 assert.equal((await db.query<any>("select has_function_privilege('authenticated','apply_whatsapp_webhook(text,jsonb)','EXECUTE') allowed")).rows[0].allowed,false);
}finally{await db.close();}});

test('deployment SQL: combined installer, rerun guard and first-admin script',async()=>{const db=await database(true);try{
 assert.equal((await db.query<any>('select * from pools')).rows.length,2);
 assert.equal((await db.query<any>('select * from whatsapp_templates')).rows.length,12);
 const adminSql=readFileSync('supabase/admin/CREATE_FIRST_ADMIN.sql','utf8');
 await assert.rejects(()=>db.exec(adminSql),/Replace PASTE_YOUR_AUTH_USER_UUID_HERE/);
 const configured=adminSql.replaceAll('PASTE_YOUR_AUTH_USER_UUID_HERE',BUYER).replace("if admin_user_id_text='"+BUYER+"'", "if admin_user_id_text='PASTE_YOUR_AUTH_USER_UUID_HERE'");
 await db.exec(configured);await db.exec(configured);
 assert.equal((await db.query<any>('select * from admins where user_id=$1',[BUYER])).rows.length,1);
 await assert.rejects(()=>db.exec(readFileSync('supabase/install/PLYDECK_NEW_PROJECT_SETUP.sql','utf8')),/Existing tables found/);await db.exec('rollback');
 assert.equal((await db.query<any>('select * from pools')).rows.length,2);
}finally{await db.close();}});
