export function Terms(){return <div className="terms-copy">
 <p><strong>PLYDECK direct slot booking terms · version 2026-09-direct-1</strong></p>
 <h3>1. Your reservation</h3><p>A slot contains the published fixed 100-sheet MR and BWP plywood composition; buyers cannot change its grade, thickness, size or quantity. The order summary shows the four plywood rate lines, taxable value, GST and total. Confirming a slot creates an order record and immediately locks the selected slot for your business. No online payment or payment gateway is used to make the reservation.</p>
 <h3>2. Offline payments, pool confirmation and delivery</h3><p>No payment gateway is used. PLYDECK operations verifies offline receipts and records each confirmation against the order: 10% booking, a further 40% before pool confirmation, and the final 50% after QC and before dispatch. A pool may include slots blocked by operations; every other slot must be reserved and paid to 50% before confirmation. Target delivery to the named city hub is within seven calendar days of pool confirmation, subject to the published schedule.</p>
 <h3>3. Cancellations</h3><p>If PLYDECK cancels an underfilled pool, cannot procure the agreed specification, or cancels for a supplier or QC failure, the reservation is released and any verified offline amount is handled under the cancellation policy. A buyer may cancel while the pool is live or confirming; any offline amount already received requires operations review. After supplier commitment, a cancellation request is recorded for review and the slot may be offered to the next eligible waiting-list buyer.</p>
 <h3>4. Quality, inspection and claims</h3><p>The confirmed order specification and QC report govern the goods supplied. Product imagery is representative unless marked as actual batch photographs. No substitution without consent. Record visible damage or shortages on the delivery receipt and notify PLYDECK promptly with photographs. Latent manufacturing defects remain subject to the agreed supplier warranty and applicable rights.</p>
 <h3>5. Waiting list and availability</h3><p>Availability is based on actual reservations. Joining a waiting list is free and does not guarantee stock, price or allocation. Offers follow queue order, carry a stated expiry and require a new accepted quotation. Sample occupancy is displayed only in demo mode and has no connection to paid orders.</p>
 <h3>6. Business details and privacy</h3><p>Provide accurate business name, GSTIN, billing address and contact details. These details are used for order administration, invoicing, support, supplier and logistics fulfilment, and tax obligations. PLYDECK does not collect card credentials; administrators record only offline payment method, reference, receipt date and operational notes. WhatsApp order updates are optional and sent only after an explicit opt-in. Statutory rights prevail over these terms.</p>
 </div>;}
