export function Terms(){return <div className="terms-copy">
 <p><strong>PLYDECK pool booking terms · version 2026-09-p1</strong></p>
 <h3>1. Your order and payments</h3><p>A slot contains the published fixed 100-sheet MR and BWP plywood composition; buyers cannot change its grade, thickness, size or quantity. The taxable order value includes the applicable operations allocation and PLYDECK spread, while the customer summary displays the four plywood rate lines, taxable value and GST. Pay 10% of your order total to reserve, another 40% when the pool reaches confirmation, and the final 50% after the QC report is released, before dispatch. An unpaid checkout hold expires after 15 minutes. A successful, verified payment is required to reserve a slot.</p>
 <h3>2. Confirmation and delivery</h3><p>The pool moves to confirmation when all slots are reserved. The 40% instalment is due within 48 hours of the confirmation notice. Once all required 50% payments clear and the supplier accepts the order, PLYDECK confirms the pool. Target delivery to the named city hub is within seven calendar days of that confirmation, subject to the published schedule. The final 50% is due within 48 hours of the QC notice. Dispatch requires cleared full payment. Hub collection is due within 48 hours of the ready notice; any agreed extra storage or local delivery is separately quoted.</p>
 <h3>3. Refundable cancellations</h3><p>If PLYDECK cancels an underfilled pool, cannot procure the agreed specification, or cancels for a supplier or QC failure, all amounts collected for the undelivered goods are refundable. A buyer may request a full refund before pool confirmation and supplier commitment. Duplicate, excess or late payments that cannot secure a slot are refundable. A material change to specification, price or delivery schedule requires buyer consent; if declined before fulfilment, the affected undelivered order is refundable. Approved refunds are initiated to the original payment method within seven business days; bank settlement may take longer.</p>
 <h3>4. Buyer cancellation or payment default after confirmation</h3><p>After pool confirmation, receipt of 50% and supplier commitment, the first 50% is treated as a non-refundable commitment for buyer-initiated cancellation or failure to pay after QC, subject to applicable law and reasonable compensation for the loss incurred. PLYDECK records the default, gives written notice and a further 48-hour cure period before cancelling the allocation. The slot may then be offered to the next eligible buyer on the waiting list. Any retention is reviewed against committed costs and recovery through resale, with any refundable balance returned. This clause does not permit forfeiture where PLYDECK or the supplier fails to fulfil the agreed order.</p>
 <h3>5. Quality, inspection and claims</h3><p>The confirmed order specification and QC report govern the goods supplied. Product imagery is representative unless marked as actual batch photographs. No substitution without consent. Record visible damage or shortages on the delivery receipt and notify PLYDECK promptly with photographs. Latent manufacturing defects remain subject to the agreed supplier warranty and applicable rights; final payment does not waive a valid defect claim.</p>
 <h3>6. Waiting list and availability</h3><p>Availability is based on actual reservations and active checkout holds. Joining a waiting list is free and does not guarantee stock or price. Offers follow queue order, carry a stated expiry and require a new accepted quotation. Sample occupancy is displayed only in demo mode and has no connection to paid orders.</p>
 <h3>7. Business details and privacy</h3><p>Provide accurate business name, GSTIN, billing address and contact details. These details are used for order administration, invoicing, support, supplier and logistics fulfilment, and payment processing. PLYDECK does not collect or store card credentials. Contact PLYDECK using the contact details on your order confirmation. WhatsApp order updates are optional and sent only after an explicit opt-in; you can withdraw consent under Business details. Statutory rights prevail over these terms.</p>
 </div>;}
