import {z} from 'zod';
import {adminIdentity,serverDb,ok,failure,jsonBody,rpc,HttpError,limit} from '@/lib/server';
import {poolSchema,categorySchema,shipmentSchema} from '@/lib/validation';
export async function POST(request:Request){try{const user=await adminIdentity(request);await limit(user.id,'admin',50);const body=await jsonBody(request);switch(body.action){
 case 'save':{if(body.entity==='pools')return ok(await rpc('save_pool',{p_admin:user.id,p_record:poolSchema.parse(body.record)}));if(body.entity==='shipments')return ok(await rpc('save_shipment',{p_admin:user.id,p_record:shipmentSchema.parse(body.record)}));if(body.entity==='categories'){const value=categorySchema.parse(body.record);const db=serverDb();const{error}=await db.from('categories').upsert(value);if(error)throw error;await db.from('audit_log').insert({actor:user.id,action:'save_category',entity_id:value.id,payload:value});return ok({saved:true});}throw new HttpError(400,'Unknown entity.');}
 case 'transition':{const v=z.object({pool_id:z.uuid(),event:z.enum(['publish','request_confirmation','confirm','qc','dispatch','cancel']),note:z.string().max(10000).default('')}).parse(body);return ok(await rpc('transition_pool',{p_admin:user.id,p_pool:v.pool_id,p_event:v.event,p_note:v.note}));}
 case 'slot_block':{const v=z.object({pool_id:z.uuid(),slot_no:z.number().int().min(1).max(100),blocked:z.boolean(),reason:z.string().trim().max(500).default('')}).parse(body);return ok(await rpc('manage_blocked_slot',{p_admin:user.id,p_pool:v.pool_id,p_slot:v.slot_no,p_block:v.blocked,p_reason:v.reason}));}
 case 'manual_payment':{const v=z.object({order_id:z.uuid(),stage:z.enum(['booking','confirmation','final']),method:z.enum(['bank_transfer','upi','cash','cheque','other']),reference:z.string().trim().min(2).max(200),note:z.string().trim().max(1000).default(''),received_at:z.iso.datetime({offset:true})}).parse(body);return ok(await rpc('record_manual_payment',{p_admin:user.id,p_order:v.order_id,p_stage:v.stage,p_method:v.method,p_reference:v.reference,p_note:v.note,p_received_at:v.received_at}));}
 case 'offer_next':return ok(await rpc('offer_next',{p_admin:user.id,p_pool:z.uuid().parse(body.pool_id)}));
 default:throw new HttpError(400,'Unknown action.');}}catch(e){return failure(e);}}
